sudo: required

language: node_js
node_js:
  - 8

service:
  - docker

script:
  - npm run lint
  - docker build -t club_api_v1 .

deploy:
  provider: heroku
  api_key:
    secure: 8c6ff897-6709-4936-bac7-c74ef30dd5dd
  on: dockerizing

notifications:
  slack: universitekulup:8NUVUuPGozbZa3wvkUNsMeCn