sudo: required

language: node_js
node_js:
  - 8

service:
  - docker

script:
  - npm run lint
  - docker build -t club_api_v1 .
  - docker ps

notifications:
  slack: universitekulup:8NUVUuPGozbZa3wvkUNsMeCn