sudo: required

language: node_js
node_js:
  - 8

service:
  - docker

script:
  - npm run lint
  - docker build -t club_api_v1 .
  - echo "Build Done"
  - docker images
  - echo "Images Done"
  - docker ps
  - echo "ps Done"

notifications:
  slack: universitekulup:8NUVUuPGozbZa3wvkUNsMeCn